#!/usr/bin/env ruby

require 'mechanize'
require 'fileutils'

Dir.mkdir("results") unless Dir.exist?("results")
Dir.chdir("results")
File.new("output.txt","a+") if ARGV.length < 3
mechanize = Mechanize.new
exit unless ARGV[0].match(/https?:\/\/[\S].[\S]/)
page = mechanize.get(ARGV[0])
page.links.each do |link|
  if link.text.match(ARGV[1])
    ARGV.length < 3 ? File.open("output.txt", "a+") :  File.open(ARGV[2], "a+") do |f|
      f.puts "#{link.text} - #{link.uri}"
    end
  end
end


