#!/usr/bin/env ruby

usless_words = %w{the a by on for of are with just but and to the my I has some in}
seps = %W(, . ! ? ( ) : ;)
p_seps = %W(. ! ?)
lines = File.readlines(ARGV[0])
text = lines.join
chars = text.scan(/./).length
chars_non_space = text.gsub(/\s+/,"").length
words = text.split.length
usful_words = usless_words.each { |word | text.delete(word)}.length
paragraphs = text.split(/\n\n/).length
sentences = text.split(/\.|\?|!/).length - 1
lines_count = lines.size
spp_average = sentences/paragraphs
wps_average = words/sentences

puts "#{lines_count} lines"
puts "#{chars} characters"
puts "#{chars_non_space} characters excluding spaces"
puts "#{words} words"
puts "#{usful_words} useful words"
puts "#{paragraphs} paragraphs"
puts "#{sentences} sentences"
puts "#{spp_average} sentences per paragraph (average)"
puts "#{wps_average} words per sentence (average)"
